version: 1
disable_existing_loggers: false

formatters:
  color:
    "()": "uvicorn.logging.DefaultFormatter"
    format: "%(levelprefix)s %(name)s: %(message)s"
    use_colors: true

handlers:
  console:
    class: logging.StreamHandler
    formatter: color
    stream: ext://sys.stdout

loggers:
  openui:
    level: DEBUG
    handlers: [console]
    propagate: no
  uvicorn:
    level: DEBUG
    handlers: [console]
    propagate: no

root:
  level: WARNING
  handlers: [console]