services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_VOLUME_PATH:-ollama}:/root/.ollama

  openui:
    container_name: openui
    image: ghcr.io/wandb/openui:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7878:7878"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OPENAI_API_KEY
      - ANTHROPIC_API_KEY
      - GROQ_API_KEY
    networks:
      - code-execution
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - ${DOCKER_GROUP_ID:-999}  # Default Docker group ID on most systems

  code-executor:
    build:
      context: ./backend
      dockerfile: Dockerfile.python
    security_opt:
      - no-new-privileges
    read_only: true
    tmpfs:
      - /tmp
      - /app/execution
    networks:
      - code-execution
    restart: always

networks:
  code-execution:
    name: code-execution

volumes:
  ollama:
